### ISSUE TITLE
Is Chrono reliably working past millis() rollback/overflow (+47days) ?

### ISSUE THREAD

**Issue by jodege** [thomasfredericks/Chrono#14]
I wish use for lengthy periods (+6months) without controller reboot.

**Comment by sofian** [comment]
By default it uses the basic millis() function. However you can use a function pointer instead so you could design your own timing function using a RTC for example.

**Comment by thomasfredericks** [comment]
Because of overflow math, the timer should function properly. Here is an explanation:

Chrono uses the following code `(millis() - previous_millis >= interval_millis)` to calculate if a Chrono has passed a certain interval. 

The maximum value for an unsigned long is 4,294,967,295. If you add 1 to 4,294,967,295, you rollover to 0. If you subtract 1 to 0, you get 4,294,967,295.

For an actual example, lets say that `previous_millis` = 4,294,967,200 and `interval_millis` = 100:
* If millis() is 4,294,967,250, `millis() - previous_millis` gives (4,294,967,250  - 4,294,967,200) = 50 and the function will return false (i.e. has not passed the interval of 100)
* Once millis() overflows and reaches 0, `millis() - previous_millis` returns (0 - 4,294,967,200) = -4,294,967,200 = 96 with overflow and will return false (i.e. has not passed the interval)
* Once millis() reaches 4, `millis() - previous_millis` returns (4 - 4,294,967,200) = -4,294,967,196 = 100 with overflow and this will return true (i.e. has passed the interval)
