### ISSUE TITLE
V1.01 is not available in Arduino Library Manager

### ISSUE THREAD

**Issue by Josephur** [thomasfredericks/Chrono#8]
1.0.0 is listed but not 1.0.1, so I would assume that means if someone uses the example code out there that requires start() it may cause issues?

**Comment by per1234** [comment]
The reason V1.01 is not available for installation via Library Manager is the library.properties [`version`](https://github.com/SofaPirate/Chrono/blob/V1.01/library.properties#L2) value was not updated before the release was made.

Another problem that might be encountered is "1.01" is not considered a valid version number by the Arduino IDE due to the leading zero. I recommend always using semver-compliant versioning:
https://semver.org/

**Comment by thomasfredericks** [comment]
Fixed. Will see if the semver version is more _up to date_ in the Arduino IDE.
